// Actual candidate HTML JavaScript, offline clock and DOM. No browser/account access.
const fs=require('fs'),vm=require('vm'),assert=require('assert');
const fixture=JSON.parse(fs.readFileSync(__dirname+'/candidate_ui_fixture.json','utf8'));
const results=[],elements=new Map();
function element(){return {style:{},dataset:{},textContent:'',hidden:false,clientWidth:1000,replaceChildren(){},append(){},getContext(){return new Proxy({},{get:()=>()=>{}})}}}
const document={getElementById(id){if(!elements.has(id))elements.set(id,element());return elements.get(id)},createElement:element,querySelectorAll(){return []}};
let wall=fixture.epoch,mono=500;
class Clock extends Date{static now(){return wall*1000}}
const sandbox={document,devicePixelRatio:1,window:{devicePixelRatio:1},Date:Clock,Number,Math,Set,performance:{now(){return mono*1000}},sessionStorage:{getItem(){return null},setItem(){}},setInterval(){},fetch:async()=>{throw Error('offline')},fixture};
vm.createContext(sandbox);
const html=fs.readFileSync(__dirname+'/outputs/copilot_remediation_candidate/btc_copilot.html','utf8');
vm.runInContext(html.match(/<script>([\s\S]*?)<\/script>/)[1].replace('window.onresize=draw;update();','window.onresize=draw;'),sandbox);
function run(name,fn){try{fn();results.push({scenario:name,passed:true})}catch(e){results.push({scenario:name,passed:false,error:String(e)})}}
function reset(){wall=fixture.epoch;mono=500;vm.runInContext('latest=null;receivedAt=null;receivedWall=null;disconnected=true',sandbox)}
run('valid snapshot renders and remains explicitly shadow only',()=>{reset();vm.runInContext('render(fixture)',sandbox);assert.equal(elements.get('stale').style.display,'none');assert.equal(elements.get('decision').textContent,'NO TRADE');assert.equal(elements.get('signalAlert').textContent,'')});
const bad=[['missing epoch','delete s.epoch'],['missing expiry','delete s.valid_until_epoch'],['NaN epoch','s.epoch=NaN'],['infinite expiry','s.valid_until_epoch=Infinity'],['string epoch','s.epoch=String(s.epoch)'],['boolean epoch','s.epoch=true'],['future epoch','s.epoch+=100;s.valid_until_epoch+=100'],['expired','s.epoch-=30;s.valid_until_epoch-=30'],['reversed expiry','s.valid_until_epoch=s.epoch'],['extended TTL','s.valid_until_epoch=s.epoch+100'],['missing close','delete s.close_time'],['malformed close','s.close_time="INVALID"'],['expiry past close','s.close_time=new Date(s.epoch*1000).toISOString()'],['forged directional decision','s.decision="UP"'],['forged validation','s.validation.status="VALIDATED"'],['forged position advice','s.position.guidance_valid=true'],['error flag','s.error="offline"']];
for(const [name,code] of bad)run(name,()=>{reset();assert.equal(vm.runInContext('var s=JSON.parse(JSON.stringify(fixture));'+code+';sourceFresh(s)',sandbox),false);vm.runInContext('latest=s;disconnected=false;freshness()',sandbox);assert.equal(elements.get('decision').textContent,'NO TRADE');assert.equal(elements.get('stale').style.display,'block');assert.equal(elements.get('previewCard').hidden,true)});
run('monotonic expiry',()=>{reset();vm.runInContext('render(fixture)',sandbox);mono+=20;wall+=20;vm.runInContext('freshness()',sandbox);assert.equal(elements.get('stale').style.display,'block')});
run('wall clock moves backwards after render',()=>{reset();vm.runInContext('render(fixture)',sandbox);wall-=2;mono+=1;vm.runInContext('freshness()',sandbox);assert.equal(elements.get('stale').style.display,'block')});
run('clock skew while source TTL still valid',()=>{reset();vm.runInContext('render(fixture)',sandbox);wall+=1;mono+=4;vm.runInContext('freshness()',sandbox);assert.equal(elements.get('stale').style.display,'block')});
run('disconnection suppresses prior fresh view',()=>{reset();vm.runInContext('render(fixture);disconnected=true;freshness()',sandbox);assert.equal(elements.get('stale').style.display,'block');assert.equal(elements.get('previewCard').hidden,true)});
(async()=>{run('malformed response rejected',()=>{reset();assert.throws(()=>vm.runInContext('render({})',sandbox))});reset();vm.runInContext('render(fixture)',sandbox);await vm.runInContext('update()',sandbox);run('network outage safe display',()=>{assert.equal(elements.get('stale').style.display,'block');assert.equal(elements.get('decision').textContent,'NO TRADE');assert.equal(elements.get('previewCard').hidden,true)});fs.writeFileSync(__dirname+'/candidate_ui_results.json',JSON.stringify(results,null,2));console.log(JSON.stringify({run:results.length,passed:results.filter(x=>x.passed).length,failures:results.filter(x=>!x.passed)},null,2));process.exitCode=results.every(x=>x.passed)?0:1})()
